version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=poc_pa_xpe
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  migrations:
    build: ./backend
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=poc_pa_xpe
      - DB_USER=admin
      - DB_PASSWORD=password123
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - postgres
    command: ["npm", "run", "migrate"]
    restart: "no"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://admin:password123@postgres:5432/poc_pa_xpe
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=poc_pa_xpe
      - DB_USER=admin
      - DB_PASSWORD=password123
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - postgres
      - migrations

  mobile:
    build: ./mobile
    ports:
      - "8081:8081"    # Expo development server
      - "19000:19000"  # Expo tunnel
      - "19001:19001"  # Expo tunnel
      - "19002:19002"  # Expo tunnel
    volumes:
      - ./mobile:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
